### PR TITLE
RocksDB scan fix

### PR DESCRIPTION
**Pull request by dispalt**
I should probably add a test to expose the issue so it doesn't creep back in.

### CODE REVIEW

**Comment by vigoo** [comment]
Made a new rocksdb release (`0.4.3`), can you change the dependency and run `sbt fmt`?

**Comment by dispalt** [comment]
Done @vigoo!

**Comment by dispalt** [comment]
@vigoo there seems to be an extra element returned via the rocksdb bindings, any good ideas on that one?  It might be an issue with the bindings themselves.

**Comment by dispalt** [comment]
Nice work. Yeah I wasn't sure how much you wanted to go down the doing your own schema rabbit hole, but this looks great.

**Pull request merged**
