### PR TITLE
Implemented key-value store for DynamoDB.

### PR DESCRIPTION
**Pull request by ithinkicancode**
TODO:

- [x] Write doc

### CODE REVIEW

**Review by adamgfraser — DISMISSED** [review]
@ithinkicancode Do you want to do more work on this or shall we merge it now?

**Comment by ithinkicancode** [comment]
> @ithinkicancode Do you want to do more work on this or shall we merge it now?

Hi Adam, I'll add some docs and comments in the evening.

**Comment by adamgfraser** [comment]
@ithinkicancode Sounds good!

**Comment by ithinkicancode** [comment]
@adamgfraser Comments and docs added.

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
